### PR TITLE
chore: update node version in .nvmrc & CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Ref: #579, a5a066c69dc422e0abd3127f281c119a8ddfa241

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hello @JadTermsani, do you have a minute to review this PR? Thank you ;)

**Comment by JadTermsani** [comment]
@PeterDaveHello I think it's better to specify version 12.8.1 that we're using

**Comment by PeterDaveHello** [comment]
@JadTermsani, thanks for your review, and commit revised as suggested.

BTW, just thought maybe not stick to the patch version will keep the things more up-to-date as by following semantic versioning, stick to the major version shouldn't break things in most cases?

**Review by JadTermsani — APPROVED** [review]

**Comment by JadTermsani** [comment]
@PeterDaveHello agreed. But thought of keeping everything aligned. ty!

**Pull request merged**
