### PR TITLE
Feat: pitchfork extractor

### PR DESCRIPTION
**Pull request by mgeraci**
Hi there!

This PR adds a custom extractor for reviews on Pitchfork, a music review site. It's a pretty simple extractor, with an author, date, image, dek, and content. I did make one editorial choice here: Pitchfork assigns each album reviewed a score (a number between 0 and 10), and I chose to prepend this score as a sentence to the start of the review. Please do let me know if there's a better way to tackle something like this!

Thanks for this great tool, and for making contributing so simple; adding a new extractor was a cinch.

Here's a screenshot of a Pitchfork review showing the score:
Screenshot 2019-06-11 15 36 25

### CODE REVIEW

**Comment by mgeraci** [comment]
I noticed that after making this PR, the new test I added is failing. I can't reproduce this locally yet, but since it's related to the time I'd guess it's a timezone issue. I'll take a look!

**Comment by adampash** [comment]
@mgeraci This is great, thanks! 

> I did make one editorial choice here: Pitchfork assigns each album reviewed a score (a number between 0 and 10), and I chose to prepend this score as a sentence to the start of the review. Please do let me know if there's a better way to tackle something like this!

Actually, we recently added a feature that allows you to extend the fields in a custom parser beyond the defaults. It's not actually implemented on any of the parsers yet, but this seems like a perfect first case! You can see how it works here:

https://github.com/postlight/mercury-parser/blob/262dda94b30cf94c180972cbcd7671758c65c9a4/src/mercury.test.js#L130-L149

**Comment by mgeraci** [comment]
@adampash Awesome, that was a really easy change; thanks for pointing it out!

When adding a custom field like this, would you recommend leaving it as is, `score: '6.2'`, or making the output more descriptive like I had when prepending to the review content, `score: 'Score: 6.2'`?

**Comment by adampash** [comment]
> When adding a custom field like this, would you recommend leaving it as is, `score: '6.2'`, or making the output more descriptive like I had when prepending to the review content, `score: 'Score: 6.2'`?

I like the way you've done it. Thanks again @mgeraci!

**Comment by mgeraci** [comment]
🎉 Thanks for the feedback, and for merging!

**Comment by samuelclay** [comment]
Thanks for adding this field, but I want to see the score in the story content and not in a field. The point of this library is that I get the story's full content in the content field and not in single-use fields that are per-site. Since the website shows the score at top I feel it would be appropriate to have the score at top of the article content. Can we move it there so users can benefit from this?

**Pull request merged**
