### PR TITLE
feat: add headersCleaner flag

### PR DESCRIPTION
**Pull request by kik0220**
Add headersCleaner flag for ignore ```cleanHeaders```.

### CODE REVIEW

**Comment by adampash** [comment]
@kik0220 Can you explain what the motivation behind this change is?

**Comment by kik0220** [comment]
Yes, I am creating an [custom extractor](https://github.com/kik0220/mercury-parser/blob/feat-watch-impress-co-jp-extractor/src/extractors/custom/watch.impress.co.jp/index.js) using this flag.

**Comment by adampash** [comment]
I need you to explain the actual use case, and why this can't be addressed using existing mechanisms available to custom parsers.

**Comment by kik0220** [comment]
Is there a way to display the h2-h6 tag in existing mechanisms?
I could not find it.

**Pull request closed without merging**
