### PR TITLE
fix: Include "src/shims" for webpack builds for web

### PR DESCRIPTION
**Pull request by a2**
I've modified the "files" array in the _package.json_ file to include the _src/shims/_ directory. I don't know if this is the right way to fix the following issue but I have confirmed that my web-targeted webpack build needed these files.

```
a2@tai-shan ~/D/Project> yarn build
yarn run v1.13.0
$ webpack
Hash: 08e953d9e20777053e94
Version: webpack 4.29.6
Time: 947ms
Built at: 03/03/2019 1:56:19 PM
 1 asset
Entrypoint main = ExtensionPreprocessing.js
 [29] (webpack)/buildin/module.js 497 bytes {0} [built]
 [73] (webpack)/buildin/global.js 472 bytes {0} [built]
[203] ./src/index.js 270 bytes {0} [built]
[244] jsdom (ignored) 15 bytes {0} [built]
[303] ./node_modules/@postlight/mercury-parser/node_modules/moment/locale sync ^\.\/.*$ 2.93 KiB {0} [optional] [built]
    + 308 hidden modules

ERROR in ./node_modules/@postlight/mercury-parser/dist/mercury.js
Module not found: Error: Can't resolve 'cheerio' in '/Users/a2/Developer/Project/node_modules/@postlight/mercury-parser/dist'
 @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 10:30-48
 @ ./src/index.js

ERROR in ./node_modules/@postlight/mercury-parser/dist/mercury.js
Module not found: Error: Can't resolve 'iconv-lite' in '/Users/a2/Developer/Project/node_modules/@postlight/mercury-parser/dist'
 @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 12:28-49
 @ ./src/index.js
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### CODE REVIEW

**Comment by a2** [comment]
Hmmm, I'm actually still seeing this issue even after referencing my fork's branch, which is odd because it worked when I did `yarn link` and `yarn link "@postlight/mercury-parser"` :/

**Comment by imWildCat** [comment]
Really need this to be fixed.

**Comment by pantchox** [comment]
basically without this nothing works...?

**Comment by imWildCat** [comment]
@pantchox In my case, almost nothing works.

I have to change the Webpack's `target` to `node` instead `web`, which is a little bit weird.

**Comment by adampash** [comment]
@a2 Apologies for the slow response, but just merged. Thank you!

**Comment by pantchox** [comment]
what about npm release?

**Comment by pantchox** [comment]
thank you for merging but @adampash you need to publish new npm package, i can't test your library although i receive many emails about it being open source.

**Comment by toufic-m** [comment]
@pantchox this fix is in the v2.1.0 release (https://github.com/postlight/mercury-parser/blob/master/CHANGELOG.md#210-apr-10-2019), which has been published on the NPM registry (https://www.npmjs.com/package/@postlight/mercury-parser/v/2.1.0). Are you using this version in your project?

**Comment by pantchox** [comment]
great, thank you!

**Comment by imWildCat** [comment]
Hi, @a2 ! Could you please give me some hint about how to use it with Webpack and build it for web?
I am using Webpack/TypeScript and it always get stuck while compiling.

**Pull request merged**
